// EXAMPLE => 
// export const CHANGE_STORE = 'CHANGE_STORE';

export const SET_ANON_USERNAME = 'SET_ANON_USERNAME';
export const LOGGEDIN = 'LOGGEDIN';
export const TOGGLE_LOGIN_LOGOUT = 'TOGGLE_LOGIN_LOGOUT';
export const SET_LOGGEDIN_PLAYERS = 'SET_LOGGEDIN_PLAYERS';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';